sources:
  - name: tpch_sf1
    meta:
      external_location: "/tmp/data/lake/{name}.parquet"
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
