INSTALL tpch;
LOAD tpch;
CALL dbgen(sf = 1);

CREATE OR REPLACE TABLE customer AS SELECT * FROM customer;
CREATE OR REPLACE TABLE lineitem AS SELECT * FROM lineitem;
CREATE OR REPLACE TABLE nation AS SELECT * FROM nation;
CREATE OR REPLACE TABLE orders AS SELECT * FROM orders;
CREATE OR REPLACE TABLE part AS SELECT * FROM part;
CREATE OR REPLACE TABLE partsupp AS SELECT * FROM partsupp;
CREATE OR REPLACE TABLE region AS SELECT * FROM region;
CREATE OR REPLACE TABLE supplier AS SELECT * FROM supplier;
